---
- name: drbdmanage_systemctl_daemon_reload
  shell: "systemctl daemon-reload"
  
- name: drbdmanage_service
  service:
    name: "{{ item }}"
    enabled: "yes"
  with_items: "{{ drbdmanage_m.services }}"
  
 
